"""remove description field

Revision ID: 8d7438b45a09
Revises: b8db73e3adc3
Create Date: 2026-08-13 17:47:40.058570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7438b45a09'
down_revision: Union[str, Sequence[str], None] = 'b8db73e3adc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
